---
name: theanswer

releases:
- name: theanswer
  version: latest

stemcells:
- alias: ubuntu-xenial
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  max_in_flight: 6
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

instance_groups:
- name: theanswer
  vm_type: default
  instances: 1
  azs: [z1]
  stemcell: ubuntu-xenial
  jobs:
  - name: theanswer
    release: theanswer
  networks:
  - name: default

properties:
  theanswer:
    port: 8080
